# 配置端口号和项目的根路径
server:
  port: 7001
  servlet:
    context-path: /ad-search

# Spring相关配置，jpa相关配置，数据源的配置
spring:
  application:
    name: eureka-client-ad-search
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/imooc_ad_data?autoReconnect=true
    username: root
    password: 1027
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
# 将应用程序注册到（服务注册中心）eureka Server
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
    enabled: false
# feign进行声明式服务调用的过程中，允许采用hystrix进行服务降级
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

# 定义和数据库相关的信息
# binlogName :binlog文件名
# position :偏移量
adconf:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: 1027
    binlogName: ""
    position: -1
  kafka:
    topic: ad-search-mysql-data
